#
#  This is the driver file for Azure DevOps 2019 build pipeline
#

pool:
  vmImage: "ubuntu-latest"

jobs:
#
# SonarCloud - Static Code Analysis
#
- job: sonarcloud_analysis
  displayName: 'SonarCloud Analysis'

  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk (for SonarCloud)'
    inputs:
      packageType: sdk
      version: 2.2.203
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk'
    inputs:
      packageType: sdk
      version: 3.0.100
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: "sonar-cloud-ctoec"
      organization: "ctoec"
      scannerMode: "MSBuild"
      projectKey: "ctoec_winged-keys"
      extraProperties: |
        sonar.exclusions=**/Migrations/**,**/DbInitializer.cs
        sonar.coverage.exclusions=**/**

  - script: npm install typescript --loglevel verbose
    displayName: "Script: npm install typescript"

  - task: DotNetCoreCLI@2
    displayName: "Script: build Winged Keys"
    inputs:
      command: build
      projects: "$(Build.SourcesDirectory)/src/WingedKeys/WingedKeys.csproj"

  - task: SonarCloudAnalyze@1

  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: "300"

#
# Package Release - build, zip & publish
#
- job: package_release
  displayName: 'Build and Package Release'

  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk'
    inputs:
      packageType: sdk
      version: 3.0.100
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - script: dotnet publish "$(Build.SourcesDirectory)/src/WingedKeys/WingedKeys.csproj" --output "$(Build.SourcesDirectory)/src/WingedKeys/dist" --configuration Release
    displayName: "Script: dotnet publish"

  - script: cp installer/aws-windows-deployment-manifest.json $(Build.SourcesDirectory)/src/WingedKeys/dist
    displayName: "Script: add installer manifest to distribution"
  - script: cp installer/iis/web.config $(Build.SourcesDirectory)/src/WingedKeys/dist
    displayName: "Script: add installer web.config to distribution"
  - script: cp -r installer $(Build.SourcesDirectory)/src/WingedKeys/dist/installer
    displayName: "Script: add installer files to distribution"

  - task: ArchiveFiles@2
    displayName: "Archive Files"
    inputs:
      rootFolderOrFile: "$(Build.SourcesDirectory)/src/WingedKeys/dist"
      includeRootFolder: false
      archiveType: "zip"
      #tarCompression: 'gz' # Optional. Options: gz, bz2, xz, none
      archiveFile: "$(Build.ArtifactStagingDirectory)/winged-keys-app.zip"
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifacts: winged-keys-app"
    inputs:
      pathToPublish: "$(Build.ArtifactStagingDirectory)/winged-keys-app.zip"
      artifactName: winged-keys-app

