version: '3'
services:
  db:
    image: mcr.microsoft.com/mssql/server
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: TestPassword1
      ACCEPT_EULA: Y
  back-end:
    build:
        context: .
        dockerfile: Dockerfile
    environment:
      ConnectionStrings__WINGEDKEYS: Server=db;Database=master;User=sa;Password=TestPassword1
    volumes:
      - ./src/WingedKeys:/app/src/WingedKeys:cached
      - ./entrypoint.sh:/entrypoint.sh
    working_dir: /app/src/WingedKeys
    ports:
      - 5050:5050
    entrypoint:
      - sh
      - /entrypoint.sh
    depends_on:
    - db